# Generated by Django 3.1 on 2020-10-23 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0003_auto_20201022_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='full_info',
            field=models.BooleanField(default=False),
        ),
    ]
