# Generated by Django 3.1 on 2020-10-23 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20201023_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone_num',
        ),
    ]
