# Generated by Django 3.1 on 2020-10-26 16:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ecom', '0009_cart_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='orderd',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Finalorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_num', models.CharField(max_length=20)),
                ('ammount', models.FloatField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('delivered', models.BooleanField(default=False)),
                ('refund_request', models.BooleanField(default=False)),
                ('refunded', models.BooleanField(default=False)),
                ('payment_method', models.CharField(max_length=10)),
                ('tnsx_id', models.CharField(max_length=50)),
                ('product', models.ManyToManyField(to='ecom.CartItem')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
