# Generated by Django 3.1 on 2020-10-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_auto_20201026_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='ammount',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='invoice_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='ecom.CartItem'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='tnsx_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
