# Generated by Django 3.1 on 2020-10-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_auto_20201027_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finalorder',
            name='invoice_num',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='payment_method',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='product',
            field=models.ManyToManyField(to='ecom.CartItem'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='tnsx_id',
            field=models.CharField(max_length=50),
        ),
    ]
