# Generated by Django 3.1 on 2020-11-01 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0016_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='district',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='extra_info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_info',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stripe_customer',
        ),
        migrations.AddField(
            model_name='profile',
            name='defult_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.shippingaddress'),
        ),
    ]
