# Generated by Django 3.1 on 2020-11-01 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0017_auto_20201101_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='default',
            field=models.BooleanField(default=False, verbose_name='Do you want to set default'),
        ),
    ]
