# Generated by Django 3.1 on 2020-11-01 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0018_auto_20201101_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='shipping_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.shippingaddress'),
        ),
    ]
