# Generated by Django 3.1 on 2020-11-01 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0019_cart_shipping_add'),
    ]

    operations = [
        migrations.AddField(
            model_name='finalorder',
            name='shipping_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ecom.shippingaddress'),
        ),
    ]
