# Generated by Django 3.1 on 2020-11-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0020_finalorder_shipping_add'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='District',
            new_name='district',
        ),
    ]
