# Generated by Django 3.1 on 2020-11-01 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0022_auto_20201101_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='order',
            field=models.ManyToManyField(blank=True, to='ecom.CartItem'),
        ),
        migrations.AlterField(
            model_name='finalorder',
            name='shipping_add',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ecom.shippingaddress'),
        ),
    ]
