# Generated by Django 3.1 on 2020-11-10 05:23

from django.db import migrations, models
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0024_auto_20201110_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='extra_image',
            field=models.ManyToManyField(to='ecom.ImageItem'),
        ),
        migrations.AddField(
            model_name='item',
            name='main_image',
            field=models.ImageField(default='default.jpg', upload_to=ecom.models.user_img_path),
        ),
    ]
