# Generated by Django 3.1 on 2020-11-11 14:55

from django.db import migrations, models
import ecom.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0026_remove_item_extra_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageitem',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=ecom.models.extra_img_path),
        ),
    ]
