# Generated by Django 3.1 on 2020-11-12 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0027_auto_20201111_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('star', models.IntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecom.profile')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ecom.item')),
            ],
        ),
    ]
